#
# example makefile for Ubuntu and perhaps many other UNIX-like systems
#
# Note: assumes you have downloaded and installed the Antlr C runtime library
# http://www.antlr.org/wiki/display/ANTLR3/Using+the+ANTLR3+C+Target
#
# and set up your path to the shared library. In my case:
# export LD_LIBRARY_PATH=/usr/local/lib:${LD_LIBRARY_PATH} 

OBJS = main.o jalLexer.o jalParser.o 

jalparser:  $(OBJS)
	$(CC) $(OBJS) -o jalparser -lantlr3c

