adc_pcfg_non18f = \
{
	'30221C' : {
	  '0000' : {
			  'RA5' : 'A',
			  'RA3' : 'A',
			  'RA2' : 'A',
			  'RA1' : 'A',
			  'RA0' : 'A',
		  },
		  '0001' : {
			  'RA5' : 'A',
			  'RA3' : 'VREF+',
			  'RA2' : 'A',
			  'RA1' : 'A',
			  'RA0' : 'A',
		  },
		  '0010' : {
			  'RA5' : 'A',
			  'RA3' : 'A',
			  'RA2' : 'A',
			  'RA1' : 'A',
			  'RA0' : 'A',
		  },
		  '0011' : {
			  'RA5' : 'A',
			  'RA3' : 'VREF+',
			  'RA2' : 'A',
			  'RA1' : 'A',
			  'RA0' : 'A',
		  },
		  '0100' : {
			  'RA5' : 'D',
			  'RA3' : 'A',
			  'RA2' : 'D',
			  'RA1' : 'A',
			  'RA0' : 'A',
		  },
		  '0101' : {
			  'RA5' : 'D',
			  'RA3' : 'VREF+',
			  'RA2' : 'D',
			  'RA1' : 'A',
			  'RA0' : 'A',
		  },
		  '011x' : {
			  'RA5' : 'D',
			  'RA3' : 'D',
			  'RA2' : 'D',
			  'RA1' : 'D',
			  'RA0' : 'D',
		  },
		  '1000' : {
			  'RA5' : 'A',
			  'RA3' : 'VREF+',
			  'RA2' : 'VREF-',
			  'RA1' : 'A',
			  'RA0' : 'A',
		  },
		  '1001' : {
			  'RA5' : 'A',
			  'RA3' : 'A',
			  'RA2' : 'A',
			  'RA1' : 'A',
			  'RA0' : 'A',
		  },
		  '1010' : {
			  'RA5' : 'A',
			  'RA3' : 'VREF+',
			  'RA2' : 'A',
			  'RA1' : 'A',
			  'RA0' : 'A',
		  },
		  '1011' : {
			  'RA5' : 'A',
			  'RA3' : 'VREF+',
			  'RA2' : 'VREF-',
			  'RA1' : 'A',
			  'RA0' : 'A',
		  },
		  '1100' : {
			  'RA5' : 'A',
			  'RA3' : 'VREF+',
			  'RA2' : 'VREF-',
			  'RA1' : 'A',
			  'RA0' : 'A',
		  },
		  '1101' : {
			  'RA5' : 'D',
			  'RA3' : 'VREF+',
			  'RA2' : 'VREF-',
			  'RA1' : 'A',
			  'RA0' : 'A',
		  },
		  '1110' : {
			  'RA5' : 'D',
			  'RA3' : 'D',
			  'RA2' : 'D',
			  'RA1' : 'D',
			  'RA0' : 'A',
		  },
		  '1111' : {
			  'RA5' : 'D',
			  'RA3' : 'VREF+',
			  'RA2' : 'VREF-',
			  'RA1' : 'D',
			  'RA0' : 'A',
		  },
	},
	'30292C' : {
		'0000' : {
				'RE2' : 'A',
				'RE1' : 'A',
				'RE0' : 'A',
				'RA5' : 'A',
				'RA3' : 'A',
				'RA2' : 'A',
				'RA1' : 'A',
				'RA0' : 'A',
		},
		'0001' : {
				'RE2' : 'A',
				'RE1' : 'A',
				'RE0' : 'A',
				'RA5' : 'A',
				'RA3' : 'VREF+',
				'RA2' : 'A',
				'RA1' : 'A',
				'RA0' : 'A',
		},
		'0010' : {
				'RE2' : 'D',
				'RE1' : 'D',
				'RE0' : 'D',
				'RA5' : 'A',
				'RA3' : 'A',
				'RA2' : 'A',
				'RA1' : 'A',
				'RA0' : 'A',
		},
		'0011' : {
				'RE2' : 'D',
				'RE1' : 'D',
				'RE0' : 'D',
				'RA5' : 'A',
				'RA3' : 'VREF+',
				'RA2' : 'A',
				'RA1' : 'A',
				'RA0' : 'A',
		},
		'0100' : {
				'RE2' : 'D',
				'RE1' : 'D',
				'RE0' : 'D',
				'RA5' : 'D',
				'RA3' : 'A',
				'RA2' : 'D',
				'RA1' : 'A',
				'RA0' : 'A',
		},
		'0101' : {
				'RE2' : 'D',
				'RE1' : 'D',
				'RE0' : 'D',
				'RA5' : 'D',
				'RA3' : 'VREF+',
				'RA2' : 'D',
				'RA1' : 'A',
				'RA0' : 'A',
		},
		'011x' : {
				'RE2' : 'D',
				'RE1' : 'D',
				'RE0' : 'D',
				'RA5' : 'D',
				'RA3' : 'D',
				'RA2' : 'D',
				'RA1' : 'D',
				'RA0' : 'D',
		},
		'1000' : {
				'RE2' : 'A',
				'RE1' : 'A',
				'RE0' : 'A',
				'RA5' : 'A',
				'RA3' : 'VREF+',
				'RA2' : 'VREF-',
				'RA1' : 'A',
				'RA0' : 'A',
		},
		'1001' : {
				'RE2' : 'D',
				'RE1' : 'D',
				'RE0' : 'A',
				'RA5' : 'A',
				'RA3' : 'A',
				'RA2' : 'A',
				'RA1' : 'A',
				'RA0' : 'A',
		},
		'1010' : {
				'RE2' : 'D',
				'RE1' : 'D',
				'RE0' : 'A',
				'RA5' : 'A',
				'RA3' : 'VREF+',
				'RA2' : 'A',
				'RA1' : 'A',
				'RA0' : 'A',
		},
		'1011' : {
				'RE2' : 'D',
				'RE1' : 'D',
				'RE0' : 'A',
				'RA5' : 'A',
				'RA3' : 'VREF+',
				'RA2' : 'VREF-',
				'RA1' : 'A',
				'RA0' : 'A',
		},
		'1100' : {
				'RE2' : 'D',
				'RE1' : 'D',
				'RE0' : 'D',
				'RA5' : 'A',
				'RA3' : 'VREF+',
				'RA2' : 'VREF-',
				'RA1' : 'A',
				'RA0' : 'A',
		},
		'1101' : {
				'RE2' : 'D',
				'RE1' : 'D',
				'RE0' : 'D',
				'RA5' : 'D',
				'RA3' : 'VREF+',
				'RA2' : 'VREF-',
				'RA1' : 'A',
				'RA0' : 'A',
		},
		'1110' : {
				'RE2' : 'D',
				'RE1' : 'D',
				'RE0' : 'D',
				'RA5' : 'D',
				'RA3' : 'D',
				'RA2' : 'D',
				'RA1' : 'D',
				'RA0' : 'A',
		},
		'1111' : {
				'RE2' : 'D',
				'RE1' : 'D',
				'RE0' : 'D',
				'RA5' : 'D',
				'RA3' : 'VREF+',
				'RA2' : 'VREF-',
				'RA1' : 'D',
				'RA0' : 'A',
		},
	},
	'30325B' : {
		 '000' : {
				'RA0' : 'A',
				'RA1' : 'A',
				'RA2' : 'A',
				'RA5' : 'A',
				'RA3' : 'A',
				'RE0' : 'A',
				'RE1' : 'A',
				'RE2' : 'A',
		 },
		 '001' : {
				'RA0' : 'A',
				'RA1' : 'A',
				'RA2' : 'A',
				'RA5' : 'A',
				'RA3' : 'VREF',
				'RE0' : 'A',
				'RE1' : 'A',
				'RE2' : 'A',
		 },
		 '010' : {
				'RA0' : 'A',
				'RA1' : 'A',
				'RA2' : 'A',
				'RA5' : 'A',
				'RA3' : 'A',
				'RE0' : 'D',
				'RE1' : 'D',
				'RE2' : 'D',
		 },
		 '011' : {
				'RA0' : 'A',
				'RA1' : 'A',
				'RA2' : 'A',
				'RA5' : 'A',
				'RA3' : 'VREF',
				'RE0' : 'D',
				'RE1' : 'D',
				'RE2' : 'D',
		 },
		 '100' : {
				'RA0' : 'A',
				'RA1' : 'A',
				'RA2' : 'D',
				'RA5' : 'D',
				'RA3' : 'A',
				'RE0' : 'D',
				'RE1' : 'D',
				'RE2' : 'D',
		 },
		 '101' : {
				'RA0' : 'A',
				'RA1' : 'A',
				'RA2' : 'D',
				'RA5' : 'D',
				'RA3' : 'VREF',
				'RE0' : 'D',
				'RE1' : 'D',
				'RE2' : 'D',
		 },
		 '11x' : {
				'RA0' : 'D',
				'RA1' : 'D',
				'RA2' : 'D',
				'RA5' : 'D',
				'RA3' : 'D',
				'RE0' : 'D',
				'RE1' : 'D',
				'RE2' : 'D',
		 },
	},
	'30498C' : {
		 '0000' : {
				'AN13/RB5' : 'A',
				'AN12/RB0' : 'A',
				'AN11/RB4' : 'A',
				'AN10/RB1' : 'A',
				'AN9/RB3' : 'A',
				'AN8/RB2' : 'A',
				'AN7/RE2' : 'A',
				'AN6/RE1' : 'A',
				'AN5/RE0' : 'A',
				'AN4/RA5' : 'A',
				'AN3/RA3' : 'A',
				'AN2/RA2' : 'A',
				'AN1/RA1' : 'A',
				'AN0/RA0' : 'A',
		 },
		 '0001' : {
				'AN13/RB5' : 'A',
				'AN12/RB0' : 'A',
				'AN11/RB4' : 'A',
				'AN10/RB1' : 'A',
				'AN9/RB3' : 'A',
				'AN8/RB2' : 'A',
				'AN7/RE2' : 'A',
				'AN6/RE1' : 'A',
				'AN5/RE0' : 'A',
				'AN4/RA5' : 'A',
				'AN3/RA3' : 'A',
				'AN2/RA2' : 'A',
				'AN1/RA1' : 'A',
				'AN0/RA0' : 'A',
		 },
		 '0010' : {
				'AN13/RB5' : 'D',
				'AN12/RB0' : 'A',
				'AN11/RB4' : 'A',
				'AN10/RB1' : 'A',
				'AN9/RB3' : 'A',
				'AN8/RB2' : 'A',
				'AN7/RE2' : 'A',
				'AN6/RE1' : 'A',
				'AN5/RE0' : 'A',
				'AN4/RA5' : 'A',
				'AN3/RA3' : 'A',
				'AN2/RA2' : 'A',
				'AN1/RA1' : 'A',
				'AN0/RA0' : 'A',
		 },
		 '0011' : {
				'AN13/RB5' : 'D',
				'AN12/RB0' : 'D',
				'AN11/RB4' : 'A',
				'AN10/RB1' : 'A',
				'AN9/RB3' : 'A',
				'AN8/RB2' : 'A',
				'AN7/RE2' : 'A',
				'AN6/RE1' : 'A',
				'AN5/RE0' : 'A',
				'AN4/RA5' : 'A',
				'AN3/RA3' : 'A',
				'AN2/RA2' : 'A',
				'AN1/RA1' : 'A',
				'AN0/RA0' : 'A',
		 },
		 '0100' : {
				'AN13/RB5' : 'D',
				'AN12/RB0' : 'D',
				'AN11/RB4' : 'D',
				'AN10/RB1' : 'A',
				'AN9/RB3' : 'A',
				'AN8/RB2' : 'A',
				'AN7/RE2' : 'A',
				'AN6/RE1' : 'A',
				'AN5/RE0' : 'A',
				'AN4/RA5' : 'A',
				'AN3/RA3' : 'A',
				'AN2/RA2' : 'A',
				'AN1/RA1' : 'A',
				'AN0/RA0' : 'A',
		 },
		 '0101' : {
				'AN13/RB5' : 'D',
				'AN12/RB0' : 'D',
				'AN11/RB4' : 'D',
				'AN10/RB1' : 'D',
				'AN9/RB3' : 'A',
				'AN8/RB2' : 'A',
				'AN7/RE2' : 'A',
				'AN6/RE1' : 'A',
				'AN5/RE0' : 'A',
				'AN4/RA5' : 'A',
				'AN3/RA3' : 'A',
				'AN2/RA2' : 'A',
				'AN1/RA1' : 'A',
				'AN0/RA0' : 'A',
		 },
		 '0110' : {
				'AN13/RB5' : 'D',
				'AN12/RB0' : 'D',
				'AN11/RB4' : 'D',
				'AN10/RB1' : 'D',
				'AN9/RB3' : 'D',
				'AN8/RB2' : 'A',
				'AN7/RE2' : 'A',
				'AN6/RE1' : 'A',
				'AN5/RE0' : 'A',
				'AN4/RA5' : 'A',
				'AN3/RA3' : 'A',
				'AN2/RA2' : 'A',
				'AN1/RA1' : 'A',
				'AN0/RA0' : 'A',
		 },
		 '0111' : {
				'AN13/RB5' : 'D',
				'AN12/RB0' : 'D',
				'AN11/RB4' : 'D',
				'AN10/RB1' : 'D',
				'AN9/RB3' : 'D',
				'AN8/RB2' : 'D',
				'AN7/RE2' : 'A',
				'AN6/RE1' : 'A',
				'AN5/RE0' : 'A',
				'AN4/RA5' : 'A',
				'AN3/RA3' : 'A',
				'AN2/RA2' : 'A',
				'AN1/RA1' : 'A',
				'AN0/RA0' : 'A',
		 },
		 '1000' : {
				'AN13/RB5' : 'D',
				'AN12/RB0' : 'D',
				'AN11/RB4' : 'D',
				'AN10/RB1' : 'D',
				'AN9/RB3' : 'D',
				'AN8/RB2' : 'D',
				'AN7/RE2' : 'D',
				'AN6/RE1' : 'A',
				'AN5/RE0' : 'A',
				'AN4/RA5' : 'A',
				'AN3/RA3' : 'A',
				'AN2/RA2' : 'A',
				'AN1/RA1' : 'A',
				'AN0/RA0' : 'A',
		 },
		 '1001' : {
				'AN13/RB5' : 'D',
				'AN12/RB0' : 'D',
				'AN11/RB4' : 'D',
				'AN10/RB1' : 'D',
				'AN9/RB3' : 'D',
				'AN8/RB2' : 'D',
				'AN7/RE2' : 'D',
				'AN6/RE1' : 'D',
				'AN5/RE0' : 'A',
				'AN4/RA5' : 'A',
				'AN3/RA3' : 'A',
				'AN2/RA2' : 'A',
				'AN1/RA1' : 'A',
				'AN0/RA0' : 'A',
		 },
		 '1010' : {
				'AN13/RB5' : 'D',
				'AN12/RB0' : 'D',
				'AN11/RB4' : 'D',
				'AN10/RB1' : 'D',
				'AN9/RB3' : 'D',
				'AN8/RB2' : 'D',
				'AN7/RE2' : 'D',
				'AN6/RE1' : 'D',
				'AN5/RE0' : 'D',
				'AN4/RA5' : 'A',
				'AN3/RA3' : 'A',
				'AN2/RA2' : 'A',
				'AN1/RA1' : 'A',
				'AN0/RA0' : 'A',
		 },
		 '1011' : {
				'AN13/RB5' : 'D',
				'AN12/RB0' : 'D',
				'AN11/RB4' : 'D',
				'AN10/RB1' : 'D',
				'AN9/RB3' : 'D',
				'AN8/RB2' : 'D',
				'AN7/RE2' : 'D',
				'AN6/RE1' : 'D',
				'AN5/RE0' : 'D',
				'AN4/RA5' : 'D',
				'AN3/RA3' : 'A',
				'AN2/RA2' : 'A',
				'AN1/RA1' : 'A',
				'AN0/RA0' : 'A',
		 },
		 '1100' : {
				'AN13/RB5' : 'D',
				'AN12/RB0' : 'D',
				'AN11/RB4' : 'D',
				'AN10/RB1' : 'D',
				'AN9/RB3' : 'D',
				'AN8/RB2' : 'D',
				'AN7/RE2' : 'D',
				'AN6/RE1' : 'D',
				'AN5/RE0' : 'D',
				'AN4/RA5' : 'D',
				'AN3/RA3' : 'D',
				'AN2/RA2' : 'A',
				'AN1/RA1' : 'A',
				'AN0/RA0' : 'A',
		 },
		 '1101' : {
				'AN13/RB5' : 'D',
				'AN12/RB0' : 'D',
				'AN11/RB4' : 'D',
				'AN10/RB1' : 'D',
				'AN9/RB3' : 'D',
				'AN8/RB2' : 'D',
				'AN7/RE2' : 'D',
				'AN6/RE1' : 'D',
				'AN5/RE0' : 'D',
				'AN4/RA5' : 'D',
				'AN3/RA3' : 'D',
				'AN2/RA2' : 'D',
				'AN1/RA1' : 'A',
				'AN0/RA0' : 'A',
		 },
		 '1110' : {
				'AN13/RB5' : 'D',
				'AN12/RB0' : 'D',
				'AN11/RB4' : 'D',
				'AN10/RB1' : 'D',
				'AN9/RB3' : 'D',
				'AN8/RB2' : 'D',
				'AN7/RE2' : 'D',
				'AN6/RE1' : 'D',
				'AN5/RE0' : 'D',
				'AN4/RA5' : 'D',
				'AN3/RA3' : 'D',
				'AN2/RA2' : 'D',
				'AN1/RA1' : 'D',
				'AN0/RA0' : 'A',
		 },
		 '1111' : {
				'AN13/RB5' : 'D',
				'AN12/RB0' : 'D',
				'AN11/RB4' : 'D',
				'AN10/RB1' : 'D',
				'AN9/RB3' : 'D',
				'AN8/RB2' : 'D',
				'AN7/RE2' : 'D',
				'AN6/RE1' : 'D',
				'AN5/RE0' : 'D',
				'AN4/RA5' : 'D',
				'AN3/RA3' : 'D',
				'AN2/RA2' : 'D',
				'AN1/RA1' : 'D',
				'AN0/RA0' : 'D',
		 },
	},
	'30569B' : {
		'0000' : {
				'RE2' : 'A',
				'RE1' : 'A',
				'RE0' : 'A',
				'RA5' : 'A',
				'RA3' : 'A',
				'RA2' : 'A',
				'RA1' : 'A',
				'RA0' : 'A',
		 },
		'0001' : {
				'RE2' : 'A',
				'RE1' : 'A',
				'RE0' : 'A',
				'RA5' : 'A',
				'RA3' : 'VREF+',
				'RA2' : 'A',
				'RA1' : 'A',
				'RA0' : 'A',
		 },
		'0010' : {
				'RE2' : 'D',
				'RE1' : 'D',
				'RE0' : 'D',
				'RA5' : 'A',
				'RA3' : 'A',
				'RA2' : 'A',
				'RA1' : 'A',
				'RA0' : 'A',
		 },
		'0011' : {
				'RE2' : 'D',
				'RE1' : 'D',
				'RE0' : 'D',
				'RA5' : 'A',
				'RA3' : 'VREF+',
				'RA2' : 'A',
				'RA1' : 'A',
				'RA0' : 'A',
		 },
		'0100' : {
				'RE2' : 'D',
				'RE1' : 'D',
				'RE0' : 'D',
				'RA5' : 'D',
				'RA3' : 'A',
				'RA2' : 'D',
				'RA1' : 'A',
				'RA0' : 'A',
		 },
		'0101' : {
				'RE2' : 'D',
				'RE1' : 'D',
				'RE0' : 'D',
				'RA5' : 'D',
				'RA3' : 'VREF+',
				'RA2' : 'D',
				'RA1' : 'A',
				'RA0' : 'A',
		 },
		'011x' : {
				'RE2' : 'D',
				'RE1' : 'D',
				'RE0' : 'D',
				'RA5' : 'D',
				'RA3' : 'D',
				'RA2' : 'D',
				'RA1' : 'D',
				'RA0' : 'D',
		 },
		'1000' : {
				'RE2' : 'A',
				'RE1' : 'A',
				'RE0' : 'A',
				'RA5' : 'A',
				'RA3' : 'VREF+',
				'RA2' : 'VREF-',
				'RA1' : 'A',
				'RA0' : 'A',
		 },
		'1001' : {
				'RE2' : 'D',
				'RE1' : 'D',
				'RE0' : 'A',
				'RA5' : 'A',
				'RA3' : 'A',
				'RA2' : 'A',
				'RA1' : 'A',
				'RA0' : 'A',
		 },
		'1010' : {
				'RE2' : 'D',
				'RE1' : 'D',
				'RE0' : 'A',
				'RA5' : 'A',
				'RA3' : 'VREF+',
				'RA2' : 'A',
				'RA1' : 'A',
				'RA0' : 'A',
		 },
		'1011' : {
				'RE2' : 'D',
				'RE1' : 'D',
				'RE0' : 'A',
				'RA5' : 'A',
				'RA3' : 'VREF+',
				'RA2' : 'VREF-',
				'RA1' : 'A',
				'RA0' : 'A',
		 },
		'1100' : {
				'RE2' : 'D',
				'RE1' : 'D',
				'RE0' : 'D',
				'RA5' : 'A',
				'RA3' : 'VREF+',
				'RA2' : 'VREF-',
				'RA1' : 'A',
				'RA0' : 'A',
		 },
		'1101' : {
				'RE2' : 'D',
				'RE1' : 'D',
				'RE0' : 'D',
				'RA5' : 'D',
				'RA3' : 'VREF+',
				'RA2' : 'VREF-',
				'RA1' : 'A',
				'RA0' : 'A',
		 },
		'1110' : {
				'RE2' : 'D',
				'RE1' : 'D',
				'RE0' : 'D',
				'RA5' : 'D',
				'RA3' : 'D',
				'RA2' : 'D',
				'RA1' : 'D',
				'RA0' : 'A',
		 },
		'1111' : {
				'RE2' : 'D',
				'RE1' : 'D',
				'RE0' : 'D',
				'RA5' : 'D',
				'RA3' : 'VREF+',
				'RA2' : 'VREF-',
				'RA1' : 'D',
				'RA0' : 'A',
		 },
	},
	'39582B' : {
		'0000' : {
				'AN7/RE2' : 'A',
				'AN6/RE1' : 'A',
				'AN5/RE0' : 'A',
				'AN4/RA5' : 'A',
				'AN3/RA3' : 'A',
				'AN2/RA2' : 'A',
				'AN1/RA1' : 'A',
				'AN0/RA0' : 'A',
		},
		'0001' : {
				'AN7/RE2' : 'A',
				'AN6/RE1' : 'A',
				'AN5/RE0' : 'A',
				'AN4/RA5' : 'A',
				'AN3/RA3' : 'VREF+',
				'AN2/RA2' : 'A',
				'AN1/RA1' : 'A',
				'AN0/RA0' : 'A',
		},
		'0010' : {
				'AN7/RE2' : 'D',
				'AN6/RE1' : 'D',
				'AN5/RE0' : 'D',
				'AN4/RA5' : 'A',
				'AN3/RA3' : 'A',
				'AN2/RA2' : 'A',
				'AN1/RA1' : 'A',
				'AN0/RA0' : 'A',
		},
		'0011' : {
				'AN7/RE2' : 'D',
				'AN6/RE1' : 'D',
				'AN5/RE0' : 'D',
				'AN4/RA5' : 'A',
				'AN3/RA3' : 'VREF+',
				'AN2/RA2' : 'A',
				'AN1/RA1' : 'A',
				'AN0/RA0' : 'A',
		},
		'0100' : {
				'AN7/RE2' : 'D',
				'AN6/RE1' : 'D',
				'AN5/RE0' : 'D',
				'AN4/RA5' : 'D',
				'AN3/RA3' : 'A',
				'AN2/RA2' : 'D',
				'AN1/RA1' : 'A',
				'AN0/RA0' : 'A',
		},
		'0101' : {
				'AN7/RE2' : 'D',
				'AN6/RE1' : 'D',
				'AN5/RE0' : 'D',
				'AN4/RA5' : 'A',
				'AN3/RA3' : 'VREF+',
				'AN2/RA2' : 'D',
				'AN1/RA1' : 'A',
				'AN0/RA0' : 'A',
		},
		'011x' : {
				'AN7/RE2' : 'D',
				'AN6/RE1' : 'D',
				'AN5/RE0' : 'D',
				'AN4/RA5' : 'D',
				'AN3/RA3' : 'D',
				'AN2/RA2' : 'D',
				'AN1/RA1' : 'D',
				'AN0/RA0' : 'D',
		},
		'1000' : {
				'AN7/RE2' : 'A',
				'AN6/RE1' : 'A',
				'AN5/RE0' : 'A',
				'AN4/RA5' : 'A',
				'AN3/RA3' : 'VREF+',
				'AN2/RA2' : 'VREF-',
				'AN1/RA1' : 'A',
				'AN0/RA0' : 'A',
		},
		'1001' : {
				'AN7/RE2' : 'D',
				'AN6/RE1' : 'D',
				'AN5/RE0' : 'A',
				'AN4/RA5' : 'A',
				'AN3/RA3' : 'A',
				'AN2/RA2' : 'A',
				'AN1/RA1' : 'A',
				'AN0/RA0' : 'A',
		},
		'1010' : {
				'AN7/RE2' : 'D',
				'AN6/RE1' : 'D',
				'AN5/RE0' : 'A',
				'AN4/RA5' : 'A',
				'AN3/RA3' : 'VREF+',
				'AN2/RA2' : 'A',
				'AN1/RA1' : 'A',
				'AN0/RA0' : 'A',
		},
		'1011' : {
				'AN7/RE2' : 'D',
				'AN6/RE1' : 'D',
				'AN5/RE0' : 'A',
				'AN4/RA5' : 'A',
				'AN3/RA3' : 'VREF+',
				'AN2/RA2' : 'VREF-',
				'AN1/RA1' : 'A',
				'AN0/RA0' : 'A',
		},
		'1100' : {
				'AN7/RE2' : 'D',
				'AN6/RE1' : 'D',
				'AN5/RE0' : 'D',
				'AN4/RA5' : 'A',
				'AN3/RA3' : 'VREF+',
				'AN2/RA2' : 'VREF-',
				'AN1/RA1' : 'A',
				'AN0/RA0' : 'A',
		},
		'1101' : {
				'AN7/RE2' : 'D',
				'AN6/RE1' : 'D',
				'AN5/RE0' : 'D',
				'AN4/RA5' : 'D',
				'AN3/RA3' : 'VREF+',
				'AN2/RA2' : 'VREF-',
				'AN1/RA1' : 'A',
				'AN0/RA0' : 'A',
		},
		'1110' : {
				'AN7/RE2' : 'D',
				'AN6/RE1' : 'D',
				'AN5/RE0' : 'D',
				'AN4/RA5' : 'D',
				'AN3/RA3' : 'D',
				'AN2/RA2' : 'D',
				'AN1/RA1' : 'D',
				'AN0/RA0' : 'A',
		},
		'1111' : {
				'AN7/RE2' : 'D',
				'AN6/RE1' : 'D',
				'AN5/RE0' : 'D',
				'AN4/RA5' : 'D',
				'AN3/RA3' : 'VREF+',
				'AN2/RA2' : 'VREF-',
				'AN1/RA1' : 'D',
				'AN0/RA0' : 'A',
		},
	},
	'39597C' : {
		'000' : {
				'RA0' : 'A',
				'RA1' : 'A',
				'RA2' : 'A',
				'RA5' : 'A',
				'RA3' : 'A',
		},	
		'001' : {
				'RA0' : 'A',
				'RA1' : 'A',
				'RA2' : 'A',
				'RA5' : 'A',
				'RA3' : 'VREF',
		},	
		'010' : {
				'RA0' : 'A',
				'RA1' : 'A',
				'RA2' : 'A',
				'RA5' : 'A',
				'RA3' : 'VREF',
		},	
		'011' : {
				'RA0' : 'A',
				'RA1' : 'A',
				'RA2' : 'A',
				'RA5' : 'A',
				'RA3' : 'VREF',
		},	
		'100' : {
				'RA0' : 'A',
				'RA1' : 'A',
				'RA2' : 'D',
				'RA5' : 'D',
				'RA3' : 'A',
		},	
		'101' : {
				'RA0' : 'A',
				'RA1' : 'A',
				'RA2' : 'D',
				'RA5' : 'D',
				'RA3' : 'VREF',
		},	
		'111' : {
				'RA0' : 'D',
				'RA1' : 'D',
				'RA2' : 'D',
				'RA5' : 'D',
				'RA3' : 'D',
		},	
	},
	'39598E' : {
		'0000' : {
				'AN4/RA4' : 'A',
				'AN3/RA3' : 'A',
				'AN2/RA2' : 'A',
				'AN1/RA1' : 'A',
				'AN0/RA0' : 'A',
		},
		'0001' : {
				'AN4/RA4' : 'A',
				'AN3/RA3' : 'VREF+',
				'AN2/RA2' : 'A',
				'AN1/RA1' : 'A',
				'AN0/RA0' : 'A',
		},
		'0010' : {
				'AN4/RA4' : 'A',
				'AN3/RA3' : 'A',
				'AN2/RA2' : 'A',
				'AN1/RA1' : 'A',
				'AN0/RA0' : 'A',
		},
		'0011' : {
				'AN4/RA4' : 'A',
				'AN3/RA3' : 'VREF+',
				'AN2/RA2' : 'A',
				'AN1/RA1' : 'A',
				'AN0/RA0' : 'A',
		},
		'0100' : {
				'AN4/RA4' : 'D',
				'AN3/RA3' : 'A',
				'AN2/RA2' : 'D',
				'AN1/RA1' : 'A',
				'AN0/RA0' : 'A',
		},
		'0101' : {
				'AN4/RA4' : 'D',
				'AN3/RA3' : 'VREF+',
				'AN2/RA2' : 'D',
				'AN1/RA1' : 'A',
				'AN0/RA0' : 'A',
		},
		'011x' : {
				'AN4/RA4' : 'D',
				'AN3/RA3' : 'D',
				'AN2/RA2' : 'D',
				'AN1/RA1' : 'D',
				'AN0/RA0' : 'D',
		},
		'1000' : {
				'AN4/RA4' : 'A',
				'AN3/RA3' : 'VREF+',
				'AN2/RA2' : 'VREF-',
				'AN1/RA1' : 'A',
				'AN0/RA0' : 'A',
		},
		'1001' : {
				'AN4/RA4' : 'A',
				'AN3/RA3' : 'A',
				'AN2/RA2' : 'A',
				'AN1/RA1' : 'A',
				'AN0/RA0' : 'A',
		},
		'1010' : {
				'AN4/RA4' : 'A',
				'AN3/RA3' : 'VREF+',
				'AN2/RA2' : 'A',
				'AN1/RA1' : 'A',
				'AN0/RA0' : 'A',
		},
		'1011' : {
				'AN4/RA4' : 'A',
				'AN3/RA3' : 'VREF+',
				'AN2/RA2' : 'VREF-',
				'AN1/RA1' : 'A',
				'AN0/RA0' : 'A',
		},
		'1100' : {
				'AN4/RA4' : 'A',
				'AN3/RA3' : 'VREF+',
				'AN2/RA2' : 'VREF-',
				'AN1/RA1' : 'A',
				'AN0/RA0' : 'A',
		},
		'1101' : {
				'AN4/RA4' : 'D',
				'AN3/RA3' : 'VREF+',
				'AN2/RA2' : 'VREF-',
				'AN1/RA1' : 'A',
				'AN0/RA0' : 'A',
		},
		'1110' : {
				'AN4/RA4' : 'D',
				'AN3/RA3' : 'D',
				'AN2/RA2' : 'D',
				'AN1/RA1' : 'D',
				'AN0/RA0' : 'A',
		},
		'1111' : {
				'AN4/RA4' : 'D',
				'AN3/RA3' : 'VREF+',
				'AN2/RA2' : 'VREF-',
				'AN1/RA1' : 'D',
				'AN0/RA0' : 'A',
		},
	},
	'41206B' : {
		'0x0' : {
				'RA3' : 'A',
				'RA2' : 'A',
				'RA1' : 'A',
				'RA0' : 'A',
		},
		'0x1' : {
				'RA3' : 'VREF',
				'RA2' : 'A',
				'RA1' : 'A',
				'RA0' : 'A',
		},
		'100' : {
				'RA3' : 'A',
				'RA2' : 'D',
				'RA1' : 'A',
				'RA0' : 'A',
		},
		'101' : {
				'RA3' : 'VREF',
				'RA2' : 'D',
				'RA1' : 'A',
				'RA0' : 'A',
		},
		'11x' : {
				'RA3' : 'D',
				'RA2' : 'D',
				'RA1' : 'D',
				'RA0' : 'D',
		},
	},
}

