adc_pcfg_non18f = \
{'30221C': {'0000': {'RA0': 'A',
                     'RA1': 'A',
                     'RA2': 'A',
                     'RA3': 'A',
                     'RA5': 'A'},
            '0001': {'RA0': 'A',
                     'RA1': 'A',
                     'RA2': 'A',
                     'RA3': 'VREF+',
                     'RA5': 'A'},
            '0010': {'RA0': 'A',
                     'RA1': 'A',
                     'RA2': 'A',
                     'RA3': 'A',
                     'RA5': 'A'},
            '0011': {'RA0': 'A',
                     'RA1': 'A',
                     'RA2': 'A',
                     'RA3': 'VREF+',
                     'RA5': 'A'},
            '0100': {'RA0': 'A',
                     'RA1': 'A',
                     'RA2': 'D',
                     'RA3': 'A',
                     'RA5': 'D'},
            '0101': {'RA0': 'A',
                     'RA1': 'A',
                     'RA2': 'D',
                     'RA3': 'VREF+',
                     'RA5': 'D'},
            '011x': {'RA0': 'D',
                     'RA1': 'D',
                     'RA2': 'D',
                     'RA3': 'D',
                     'RA5': 'D'},
            '1000': {'RA0': 'A',
                     'RA1': 'A',
                     'RA2': 'VREF-',
                     'RA3': 'VREF+',
                     'RA5': 'A'},
            '1001': {'RA0': 'A',
                     'RA1': 'A',
                     'RA2': 'A',
                     'RA3': 'A',
                     'RA5': 'A'},
            '1010': {'RA0': 'A',
                     'RA1': 'A',
                     'RA2': 'A',
                     'RA3': 'VREF+',
                     'RA5': 'A'},
            '1011': {'RA0': 'A',
                     'RA1': 'A',
                     'RA2': 'VREF-',
                     'RA3': 'VREF+',
                     'RA5': 'A'},
            '1100': {'RA0': 'A',
                     'RA1': 'A',
                     'RA2': 'VREF-',
                     'RA3': 'VREF+',
                     'RA5': 'A'},
            '1101': {'RA0': 'A',
                     'RA1': 'A',
                     'RA2': 'VREF-',
                     'RA3': 'VREF+',
                     'RA5': 'D'},
            '1110': {'RA0': 'A',
                     'RA1': 'D',
                     'RA2': 'D',
                     'RA3': 'D',
                     'RA5': 'D'},
            '1111': {'RA0': 'A',
                     'RA1': 'D',
                     'RA2': 'VREF-',
                     'RA3': 'VREF+',
                     'RA5': 'D'}},
 '30292C': {'0000': {'RA0': 'A',
                     'RA1': 'A',
                     'RA2': 'A',
                     'RA3': 'A',
                     'RA5': 'A',
                     'RE0': 'A',
                     'RE1': 'A',
                     'RE2': 'A'},
            '0001': {'RA0': 'A',
                     'RA1': 'A',
                     'RA2': 'A',
                     'RA3': 'VREF+',
                     'RA5': 'A',
                     'RE0': 'A',
                     'RE1': 'A',
                     'RE2': 'A'},
            '0010': {'RA0': 'A',
                     'RA1': 'A',
                     'RA2': 'A',
                     'RA3': 'A',
                     'RA5': 'A',
                     'RE0': 'D',
                     'RE1': 'D',
                     'RE2': 'D'},
            '0011': {'RA0': 'A',
                     'RA1': 'A',
                     'RA2': 'A',
                     'RA3': 'VREF+',
                     'RA5': 'A',
                     'RE0': 'D',
                     'RE1': 'D',
                     'RE2': 'D'},
            '0100': {'RA0': 'A',
                     'RA1': 'A',
                     'RA2': 'D',
                     'RA3': 'A',
                     'RA5': 'D',
                     'RE0': 'D',
                     'RE1': 'D',
                     'RE2': 'D'},
            '0101': {'RA0': 'A',
                     'RA1': 'A',
                     'RA2': 'D',
                     'RA3': 'VREF+',
                     'RA5': 'D',
                     'RE0': 'D',
                     'RE1': 'D',
                     'RE2': 'D'},
            '011x': {'RA0': 'D',
                     'RA1': 'D',
                     'RA2': 'D',
                     'RA3': 'D',
                     'RA5': 'D',
                     'RE0': 'D',
                     'RE1': 'D',
                     'RE2': 'D'},
            '1000': {'RA0': 'A',
                     'RA1': 'A',
                     'RA2': 'VREF-',
                     'RA3': 'VREF+',
                     'RA5': 'A',
                     'RE0': 'A',
                     'RE1': 'A',
                     'RE2': 'A'},
            '1001': {'RA0': 'A',
                     'RA1': 'A',
                     'RA2': 'A',
                     'RA3': 'A',
                     'RA5': 'A',
                     'RE0': 'A',
                     'RE1': 'D',
                     'RE2': 'D'},
            '1010': {'RA0': 'A',
                     'RA1': 'A',
                     'RA2': 'A',
                     'RA3': 'VREF+',
                     'RA5': 'A',
                     'RE0': 'A',
                     'RE1': 'D',
                     'RE2': 'D'},
            '1011': {'RA0': 'A',
                     'RA1': 'A',
                     'RA2': 'VREF-',
                     'RA3': 'VREF+',
                     'RA5': 'A',
                     'RE0': 'A',
                     'RE1': 'D',
                     'RE2': 'D'},
            '1100': {'RA0': 'A',
                     'RA1': 'A',
                     'RA2': 'VREF-',
                     'RA3': 'VREF+',
                     'RA5': 'A',
                     'RE0': 'D',
                     'RE1': 'D',
                     'RE2': 'D'},
            '1101': {'RA0': 'A',
                     'RA1': 'A',
                     'RA2': 'VREF-',
                     'RA3': 'VREF+',
                     'RA5': 'D',
                     'RE0': 'D',
                     'RE1': 'D',
                     'RE2': 'D'},
            '1110': {'RA0': 'A',
                     'RA1': 'D',
                     'RA2': 'D',
                     'RA3': 'D',
                     'RA5': 'D',
                     'RE0': 'D',
                     'RE1': 'D',
                     'RE2': 'D'},
            '1111': {'RA0': 'A',
                     'RA1': 'D',
                     'RA2': 'VREF-',
                     'RA3': 'VREF+',
                     'RA5': 'D',
                     'RE0': 'D',
                     'RE1': 'D',
                     'RE2': 'D'}},
 '30325B': {'000': {'RA0': 'A',
                    'RA1': 'A',
                    'RA2': 'A',
                    'RA3': 'A',
                    'RA5': 'A',
                    'RE0': 'A',
                    'RE1': 'A',
                    'RE2': 'A'},
            '001': {'RA0': 'A',
                    'RA1': 'A',
                    'RA2': 'A',
                    'RA3': 'VREF',
                    'RA5': 'A',
                    'RE0': 'A',
                    'RE1': 'A',
                    'RE2': 'A'},
            '010': {'RA0': 'A',
                    'RA1': 'A',
                    'RA2': 'A',
                    'RA3': 'A',
                    'RA5': 'A',
                    'RE0': 'D',
                    'RE1': 'D',
                    'RE2': 'D'},
            '011': {'RA0': 'A',
                    'RA1': 'A',
                    'RA2': 'A',
                    'RA3': 'VREF',
                    'RA5': 'A',
                    'RE0': 'D',
                    'RE1': 'D',
                    'RE2': 'D'},
            '100': {'RA0': 'A',
                    'RA1': 'A',
                    'RA2': 'D',
                    'RA3': 'A',
                    'RA5': 'D',
                    'RE0': 'D',
                    'RE1': 'D',
                    'RE2': 'D'},
            '101': {'RA0': 'A',
                    'RA1': 'A',
                    'RA2': 'D',
                    'RA3': 'VREF',
                    'RA5': 'D',
                    'RE0': 'D',
                    'RE1': 'D',
                    'RE2': 'D'},
            '11x': {'RA0': 'D',
                    'RA1': 'D',
                    'RA2': 'D',
                    'RA3': 'D',
                    'RA5': 'D',
                    'RE0': 'D',
                    'RE1': 'D',
                    'RE2': 'D'}},
 '30498C': {'0000': {'AN0/RA0': 'A',
                     'AN1/RA1': 'A',
                     'AN10/RB1': 'A',
                     'AN11/RB4': 'A',
                     'AN12/RB0': 'A',
                     'AN13/RB5': 'A',
                     'AN2/RA2': 'A',
                     'AN3/RA3': 'A',
                     'AN4/RA5': 'A',
                     'AN5/RE0': 'A',
                     'AN6/RE1': 'A',
                     'AN7/RE2': 'A',
                     'AN8/RB2': 'A',
                     'AN9/RB3': 'A'},
            '0001': {'AN0/RA0': 'A',
                     'AN1/RA1': 'A',
                     'AN10/RB1': 'A',
                     'AN11/RB4': 'A',
                     'AN12/RB0': 'A',
                     'AN13/RB5': 'A',
                     'AN2/RA2': 'A',
                     'AN3/RA3': 'A',
                     'AN4/RA5': 'A',
                     'AN5/RE0': 'A',
                     'AN6/RE1': 'A',
                     'AN7/RE2': 'A',
                     'AN8/RB2': 'A',
                     'AN9/RB3': 'A'},
            '0010': {'AN0/RA0': 'A',
                     'AN1/RA1': 'A',
                     'AN10/RB1': 'A',
                     'AN11/RB4': 'A',
                     'AN12/RB0': 'A',
                     'AN13/RB5': 'D',
                     'AN2/RA2': 'A',
                     'AN3/RA3': 'A',
                     'AN4/RA5': 'A',
                     'AN5/RE0': 'A',
                     'AN6/RE1': 'A',
                     'AN7/RE2': 'A',
                     'AN8/RB2': 'A',
                     'AN9/RB3': 'A'},
            '0011': {'AN0/RA0': 'A',
                     'AN1/RA1': 'A',
                     'AN10/RB1': 'A',
                     'AN11/RB4': 'A',
                     'AN12/RB0': 'D',
                     'AN13/RB5': 'D',
                     'AN2/RA2': 'A',
                     'AN3/RA3': 'A',
                     'AN4/RA5': 'A',
                     'AN5/RE0': 'A',
                     'AN6/RE1': 'A',
                     'AN7/RE2': 'A',
                     'AN8/RB2': 'A',
                     'AN9/RB3': 'A'},
            '0100': {'AN0/RA0': 'A',
                     'AN1/RA1': 'A',
                     'AN10/RB1': 'A',
                     'AN11/RB4': 'D',
                     'AN12/RB0': 'D',
                     'AN13/RB5': 'D',
                     'AN2/RA2': 'A',
                     'AN3/RA3': 'A',
                     'AN4/RA5': 'A',
                     'AN5/RE0': 'A',
                     'AN6/RE1': 'A',
                     'AN7/RE2': 'A',
                     'AN8/RB2': 'A',
                     'AN9/RB3': 'A'},
            '0101': {'AN0/RA0': 'A',
                     'AN1/RA1': 'A',
                     'AN10/RB1': 'D',
                     'AN11/RB4': 'D',
                     'AN12/RB0': 'D',
                     'AN13/RB5': 'D',
                     'AN2/RA2': 'A',
                     'AN3/RA3': 'A',
                     'AN4/RA5': 'A',
                     'AN5/RE0': 'A',
                     'AN6/RE1': 'A',
                     'AN7/RE2': 'A',
                     'AN8/RB2': 'A',
                     'AN9/RB3': 'A'},
            '0110': {'AN0/RA0': 'A',
                     'AN1/RA1': 'A',
                     'AN10/RB1': 'D',
                     'AN11/RB4': 'D',
                     'AN12/RB0': 'D',
                     'AN13/RB5': 'D',
                     'AN2/RA2': 'A',
                     'AN3/RA3': 'A',
                     'AN4/RA5': 'A',
                     'AN5/RE0': 'A',
                     'AN6/RE1': 'A',
                     'AN7/RE2': 'A',
                     'AN8/RB2': 'A',
                     'AN9/RB3': 'D'},
            '0111': {'AN0/RA0': 'A',
                     'AN1/RA1': 'A',
                     'AN10/RB1': 'D',
                     'AN11/RB4': 'D',
                     'AN12/RB0': 'D',
                     'AN13/RB5': 'D',
                     'AN2/RA2': 'A',
                     'AN3/RA3': 'A',
                     'AN4/RA5': 'A',
                     'AN5/RE0': 'A',
                     'AN6/RE1': 'A',
                     'AN7/RE2': 'A',
                     'AN8/RB2': 'D',
                     'AN9/RB3': 'D'},
            '1000': {'AN0/RA0': 'A',
                     'AN1/RA1': 'A',
                     'AN10/RB1': 'D',
                     'AN11/RB4': 'D',
                     'AN12/RB0': 'D',
                     'AN13/RB5': 'D',
                     'AN2/RA2': 'A',
                     'AN3/RA3': 'A',
                     'AN4/RA5': 'A',
                     'AN5/RE0': 'A',
                     'AN6/RE1': 'A',
                     'AN7/RE2': 'D',
                     'AN8/RB2': 'D',
                     'AN9/RB3': 'D'},
            '1001': {'AN0/RA0': 'A',
                     'AN1/RA1': 'A',
                     'AN10/RB1': 'D',
                     'AN11/RB4': 'D',
                     'AN12/RB0': 'D',
                     'AN13/RB5': 'D',
                     'AN2/RA2': 'A',
                     'AN3/RA3': 'A',
                     'AN4/RA5': 'A',
                     'AN5/RE0': 'A',
                     'AN6/RE1': 'D',
                     'AN7/RE2': 'D',
                     'AN8/RB2': 'D',
                     'AN9/RB3': 'D'},
            '1010': {'AN0/RA0': 'A',
                     'AN1/RA1': 'A',
                     'AN10/RB1': 'D',
                     'AN11/RB4': 'D',
                     'AN12/RB0': 'D',
                     'AN13/RB5': 'D',
                     'AN2/RA2': 'A',
                     'AN3/RA3': 'A',
                     'AN4/RA5': 'A',
                     'AN5/RE0': 'D',
                     'AN6/RE1': 'D',
                     'AN7/RE2': 'D',
                     'AN8/RB2': 'D',
                     'AN9/RB3': 'D'},
            '1011': {'AN0/RA0': 'A',
                     'AN1/RA1': 'A',
                     'AN10/RB1': 'D',
                     'AN11/RB4': 'D',
                     'AN12/RB0': 'D',
                     'AN13/RB5': 'D',
                     'AN2/RA2': 'A',
                     'AN3/RA3': 'A',
                     'AN4/RA5': 'D',
                     'AN5/RE0': 'D',
                     'AN6/RE1': 'D',
                     'AN7/RE2': 'D',
                     'AN8/RB2': 'D',
                     'AN9/RB3': 'D'},
            '1100': {'AN0/RA0': 'A',
                     'AN1/RA1': 'A',
                     'AN10/RB1': 'D',
                     'AN11/RB4': 'D',
                     'AN12/RB0': 'D',
                     'AN13/RB5': 'D',
                     'AN2/RA2': 'A',
                     'AN3/RA3': 'D',
                     'AN4/RA5': 'D',
                     'AN5/RE0': 'D',
                     'AN6/RE1': 'D',
                     'AN7/RE2': 'D',
                     'AN8/RB2': 'D',
                     'AN9/RB3': 'D'},
            '1101': {'AN0/RA0': 'A',
                     'AN1/RA1': 'A',
                     'AN10/RB1': 'D',
                     'AN11/RB4': 'D',
                     'AN12/RB0': 'D',
                     'AN13/RB5': 'D',
                     'AN2/RA2': 'D',
                     'AN3/RA3': 'D',
                     'AN4/RA5': 'D',
                     'AN5/RE0': 'D',
                     'AN6/RE1': 'D',
                     'AN7/RE2': 'D',
                     'AN8/RB2': 'D',
                     'AN9/RB3': 'D'},
            '1110': {'AN0/RA0': 'A',
                     'AN1/RA1': 'D',
                     'AN10/RB1': 'D',
                     'AN11/RB4': 'D',
                     'AN12/RB0': 'D',
                     'AN13/RB5': 'D',
                     'AN2/RA2': 'D',
                     'AN3/RA3': 'D',
                     'AN4/RA5': 'D',
                     'AN5/RE0': 'D',
                     'AN6/RE1': 'D',
                     'AN7/RE2': 'D',
                     'AN8/RB2': 'D',
                     'AN9/RB3': 'D'},
            '1111': {'AN0/RA0': 'D',
                     'AN1/RA1': 'D',
                     'AN10/RB1': 'D',
                     'AN11/RB4': 'D',
                     'AN12/RB0': 'D',
                     'AN13/RB5': 'D',
                     'AN2/RA2': 'D',
                     'AN3/RA3': 'D',
                     'AN4/RA5': 'D',
                     'AN5/RE0': 'D',
                     'AN6/RE1': 'D',
                     'AN7/RE2': 'D',
                     'AN8/RB2': 'D',
                     'AN9/RB3': 'D'}},
 '30569B': {'0000': {'RA0': 'A',
                     'RA1': 'A',
                     'RA2': 'A',
                     'RA3': 'A',
                     'RA5': 'A',
                     'RE0': 'A',
                     'RE1': 'A',
                     'RE2': 'A'},
            '0001': {'RA0': 'A',
                     'RA1': 'A',
                     'RA2': 'A',
                     'RA3': 'VREF+',
                     'RA5': 'A',
                     'RE0': 'A',
                     'RE1': 'A',
                     'RE2': 'A'},
            '0010': {'RA0': 'A',
                     'RA1': 'A',
                     'RA2': 'A',
                     'RA3': 'A',
                     'RA5': 'A',
                     'RE0': 'D',
                     'RE1': 'D',
                     'RE2': 'D'},
            '0011': {'RA0': 'A',
                     'RA1': 'A',
                     'RA2': 'A',
                     'RA3': 'VREF+',
                     'RA5': 'A',
                     'RE0': 'D',
                     'RE1': 'D',
                     'RE2': 'D'},
            '0100': {'RA0': 'A',
                     'RA1': 'A',
                     'RA2': 'D',
                     'RA3': 'A',
                     'RA5': 'D',
                     'RE0': 'D',
                     'RE1': 'D',
                     'RE2': 'D'},
            '0101': {'RA0': 'A',
                     'RA1': 'A',
                     'RA2': 'D',
                     'RA3': 'VREF+',
                     'RA5': 'D',
                     'RE0': 'D',
                     'RE1': 'D',
                     'RE2': 'D'},
            '011x': {'RA0': 'D',
                     'RA1': 'D',
                     'RA2': 'D',
                     'RA3': 'D',
                     'RA5': 'D',
                     'RE0': 'D',
                     'RE1': 'D',
                     'RE2': 'D'},
            '1000': {'RA0': 'A',
                     'RA1': 'A',
                     'RA2': 'VREF-',
                     'RA3': 'VREF+',
                     'RA5': 'A',
                     'RE0': 'A',
                     'RE1': 'A',
                     'RE2': 'A'},
            '1001': {'RA0': 'A',
                     'RA1': 'A',
                     'RA2': 'A',
                     'RA3': 'A',
                     'RA5': 'A',
                     'RE0': 'A',
                     'RE1': 'D',
                     'RE2': 'D'},
            '1010': {'RA0': 'A',
                     'RA1': 'A',
                     'RA2': 'A',
                     'RA3': 'VREF+',
                     'RA5': 'A',
                     'RE0': 'A',
                     'RE1': 'D',
                     'RE2': 'D'},
            '1011': {'RA0': 'A',
                     'RA1': 'A',
                     'RA2': 'VREF-',
                     'RA3': 'VREF+',
                     'RA5': 'A',
                     'RE0': 'A',
                     'RE1': 'D',
                     'RE2': 'D'},
            '1100': {'RA0': 'A',
                     'RA1': 'A',
                     'RA2': 'VREF-',
                     'RA3': 'VREF+',
                     'RA5': 'A',
                     'RE0': 'D',
                     'RE1': 'D',
                     'RE2': 'D'},
            '1101': {'RA0': 'A',
                     'RA1': 'A',
                     'RA2': 'VREF-',
                     'RA3': 'VREF+',
                     'RA5': 'D',
                     'RE0': 'D',
                     'RE1': 'D',
                     'RE2': 'D'},
            '1110': {'RA0': 'A',
                     'RA1': 'D',
                     'RA2': 'D',
                     'RA3': 'D',
                     'RA5': 'D',
                     'RE0': 'D',
                     'RE1': 'D',
                     'RE2': 'D'},
            '1111': {'RA0': 'A',
                     'RA1': 'D',
                     'RA2': 'VREF-',
                     'RA3': 'VREF+',
                     'RA5': 'D',
                     'RE0': 'D',
                     'RE1': 'D',
                     'RE2': 'D'}},
 '39582B': {'0000': {'AN0/RA0': 'A',
                     'AN1/RA1': 'A',
                     'AN2/RA2': 'A',
                     'AN3/RA3': 'A',
                     'AN4/RA5': 'A',
                     'AN5/RE0': 'A',
                     'AN6/RE1': 'A',
                     'AN7/RE2': 'A'},
            '0001': {'AN0/RA0': 'A',
                     'AN1/RA1': 'A',
                     'AN2/RA2': 'A',
                     'AN3/RA3': 'VREF+',
                     'AN4/RA5': 'A',
                     'AN5/RE0': 'A',
                     'AN6/RE1': 'A',
                     'AN7/RE2': 'A'},
            '0010': {'AN0/RA0': 'A',
                     'AN1/RA1': 'A',
                     'AN2/RA2': 'A',
                     'AN3/RA3': 'A',
                     'AN4/RA5': 'A',
                     'AN5/RE0': 'D',
                     'AN6/RE1': 'D',
                     'AN7/RE2': 'D'},
            '0011': {'AN0/RA0': 'A',
                     'AN1/RA1': 'A',
                     'AN2/RA2': 'A',
                     'AN3/RA3': 'VREF+',
                     'AN4/RA5': 'A',
                     'AN5/RE0': 'D',
                     'AN6/RE1': 'D',
                     'AN7/RE2': 'D'},
            '0100': {'AN0/RA0': 'A',
                     'AN1/RA1': 'A',
                     'AN2/RA2': 'D',
                     'AN3/RA3': 'A',
                     'AN4/RA5': 'D',
                     'AN5/RE0': 'D',
                     'AN6/RE1': 'D',
                     'AN7/RE2': 'D'},
            '0101': {'AN0/RA0': 'A',
                     'AN1/RA1': 'A',
                     'AN2/RA2': 'D',
                     'AN3/RA3': 'VREF+',
                     'AN4/RA5': 'A',
                     'AN5/RE0': 'D',
                     'AN6/RE1': 'D',
                     'AN7/RE2': 'D'},
            '011x': {'AN0/RA0': 'D',
                     'AN1/RA1': 'D',
                     'AN2/RA2': 'D',
                     'AN3/RA3': 'D',
                     'AN4/RA5': 'D',
                     'AN5/RE0': 'D',
                     'AN6/RE1': 'D',
                     'AN7/RE2': 'D'},
            '1000': {'AN0/RA0': 'A',
                     'AN1/RA1': 'A',
                     'AN2/RA2': 'VREF-',
                     'AN3/RA3': 'VREF+',
                     'AN4/RA5': 'A',
                     'AN5/RE0': 'A',
                     'AN6/RE1': 'A',
                     'AN7/RE2': 'A'},
            '1001': {'AN0/RA0': 'A',
                     'AN1/RA1': 'A',
                     'AN2/RA2': 'A',
                     'AN3/RA3': 'A',
                     'AN4/RA5': 'A',
                     'AN5/RE0': 'A',
                     'AN6/RE1': 'D',
                     'AN7/RE2': 'D'},
            '1010': {'AN0/RA0': 'A',
                     'AN1/RA1': 'A',
                     'AN2/RA2': 'A',
                     'AN3/RA3': 'VREF+',
                     'AN4/RA5': 'A',
                     'AN5/RE0': 'A',
                     'AN6/RE1': 'D',
                     'AN7/RE2': 'D'},
            '1011': {'AN0/RA0': 'A',
                     'AN1/RA1': 'A',
                     'AN2/RA2': 'VREF-',
                     'AN3/RA3': 'VREF+',
                     'AN4/RA5': 'A',
                     'AN5/RE0': 'A',
                     'AN6/RE1': 'D',
                     'AN7/RE2': 'D'},
            '1100': {'AN0/RA0': 'A',
                     'AN1/RA1': 'A',
                     'AN2/RA2': 'VREF-',
                     'AN3/RA3': 'VREF+',
                     'AN4/RA5': 'A',
                     'AN5/RE0': 'D',
                     'AN6/RE1': 'D',
                     'AN7/RE2': 'D'},
            '1101': {'AN0/RA0': 'A',
                     'AN1/RA1': 'A',
                     'AN2/RA2': 'VREF-',
                     'AN3/RA3': 'VREF+',
                     'AN4/RA5': 'D',
                     'AN5/RE0': 'D',
                     'AN6/RE1': 'D',
                     'AN7/RE2': 'D'},
            '1110': {'AN0/RA0': 'A',
                     'AN1/RA1': 'D',
                     'AN2/RA2': 'D',
                     'AN3/RA3': 'D',
                     'AN4/RA5': 'D',
                     'AN5/RE0': 'D',
                     'AN6/RE1': 'D',
                     'AN7/RE2': 'D'},
            '1111': {'AN0/RA0': 'A',
                     'AN1/RA1': 'D',
                     'AN2/RA2': 'VREF-',
                     'AN3/RA3': 'VREF+',
                     'AN4/RA5': 'D',
                     'AN5/RE0': 'D',
                     'AN6/RE1': 'D',
                     'AN7/RE2': 'D'}},
 '39597C': {'000': {'RA0': 'A',
                    'RA1': 'A',
                    'RA2': 'A',
                    'RA3': 'A',
                    'RA5': 'A'},
            '001': {'RA0': 'A',
                    'RA1': 'A',
                    'RA2': 'A',
                    'RA3': 'VREF',
                    'RA5': 'A'},
            '010': {'RA0': 'A',
                    'RA1': 'A',
                    'RA2': 'A',
                    'RA3': 'VREF',
                    'RA5': 'A'},
            '011': {'RA0': 'A',
                    'RA1': 'A',
                    'RA2': 'A',
                    'RA3': 'VREF',
                    'RA5': 'A'},
            '100': {'RA0': 'A',
                    'RA1': 'A',
                    'RA2': 'D',
                    'RA3': 'A',
                    'RA5': 'D'},
            '101': {'RA0': 'A',
                    'RA1': 'A',
                    'RA2': 'D',
                    'RA3': 'VREF',
                    'RA5': 'D'},
            '111': {'RA0': 'D',
                    'RA1': 'D',
                    'RA2': 'D',
                    'RA3': 'D',
                    'RA5': 'D'}},
 '39598E': {'0000': {'AN0/RA0': 'A',
                     'AN1/RA1': 'A',
                     'AN2/RA2': 'A',
                     'AN3/RA3': 'A',
                     'AN4/RA4': 'A'},
            '0001': {'AN0/RA0': 'A',
                     'AN1/RA1': 'A',
                     'AN2/RA2': 'A',
                     'AN3/RA3': 'VREF+',
                     'AN4/RA4': 'A'},
            '0010': {'AN0/RA0': 'A',
                     'AN1/RA1': 'A',
                     'AN2/RA2': 'A',
                     'AN3/RA3': 'A',
                     'AN4/RA4': 'A'},
            '0011': {'AN0/RA0': 'A',
                     'AN1/RA1': 'A',
                     'AN2/RA2': 'A',
                     'AN3/RA3': 'VREF+',
                     'AN4/RA4': 'A'},
            '0100': {'AN0/RA0': 'A',
                     'AN1/RA1': 'A',
                     'AN2/RA2': 'D',
                     'AN3/RA3': 'A',
                     'AN4/RA4': 'D'},
            '0101': {'AN0/RA0': 'A',
                     'AN1/RA1': 'A',
                     'AN2/RA2': 'D',
                     'AN3/RA3': 'VREF+',
                     'AN4/RA4': 'D'},
            '011x': {'AN0/RA0': 'D',
                     'AN1/RA1': 'D',
                     'AN2/RA2': 'D',
                     'AN3/RA3': 'D',
                     'AN4/RA4': 'D'},
            '1000': {'AN0/RA0': 'A',
                     'AN1/RA1': 'A',
                     'AN2/RA2': 'VREF-',
                     'AN3/RA3': 'VREF+',
                     'AN4/RA4': 'A'},
            '1001': {'AN0/RA0': 'A',
                     'AN1/RA1': 'A',
                     'AN2/RA2': 'A',
                     'AN3/RA3': 'A',
                     'AN4/RA4': 'A'},
            '1010': {'AN0/RA0': 'A',
                     'AN1/RA1': 'A',
                     'AN2/RA2': 'A',
                     'AN3/RA3': 'VREF+',
                     'AN4/RA4': 'A'},
            '1011': {'AN0/RA0': 'A',
                     'AN1/RA1': 'A',
                     'AN2/RA2': 'VREF-',
                     'AN3/RA3': 'VREF+',
                     'AN4/RA4': 'A'},
            '1100': {'AN0/RA0': 'A',
                     'AN1/RA1': 'A',
                     'AN2/RA2': 'VREF-',
                     'AN3/RA3': 'VREF+',
                     'AN4/RA4': 'A'},
            '1101': {'AN0/RA0': 'A',
                     'AN1/RA1': 'A',
                     'AN2/RA2': 'VREF-',
                     'AN3/RA3': 'VREF+',
                     'AN4/RA4': 'D'},
            '1110': {'AN0/RA0': 'A',
                     'AN1/RA1': 'D',
                     'AN2/RA2': 'D',
                     'AN3/RA3': 'D',
                     'AN4/RA4': 'D'},
            '1111': {'AN0/RA0': 'A',
                     'AN1/RA1': 'D',
                     'AN2/RA2': 'VREF-',
                     'AN3/RA3': 'VREF+',
                     'AN4/RA4': 'D'}},
 '41206B': {'0x0': {'RA0': 'A', 'RA1': 'A', 'RA2': 'A', 'RA3': 'A'},
            '0x1': {'RA0': 'A', 'RA1': 'A', 'RA2': 'A', 'RA3': 'VREF'},
            '100': {'RA0': 'A', 'RA1': 'A', 'RA2': 'D', 'RA3': 'A'},
            '101': {'RA0': 'A', 'RA1': 'A', 'RA2': 'D', 'RA3': 'VREF'},
            '11x': {'RA0': 'D', 'RA1': 'D', 'RA2': 'D', 'RA3': 'D'}}}
